version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: datalake
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: "{{ env_var('MAGE_DW_USER') }}"
  POSTGRES_PASSWORD: "{{ env_var('MAGE_DW_PASS') }}"
  POSTGRES_HOST: "{{ env_var('DW_HOST') }}"
  POSTGRES_PORT: 5432
