# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml
main:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DW_HOST') }}"
      user: "{{ env_var('MAGE_DW_USER') }}"
      password: "{{ env_var('MAGE_DW_PASS') }}"
      port: 5432
      dbname: datalake
      schema: public
      threads: 4