triggers:
- envs: []
  name: daily_dw_med_stock
  pipeline_uuid: med_stock
  schedule_interval: 0 20 * * *
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2023-11-09 00:50:00+00:00
  status: active
  variables: null
